version: '3'
services:
  mysql:
    image: "mysql:5.6"
    environment:
      MYSQL_DATABASE: mirin
      MYSQL_USER: mirin
      MYSQL_PASSWORD: mirin
      MYSQL_ROOT_PASSWORD: mirin
    ports:
      - 3306
    volumes:
      # mount ./docker/mysql with read only mode
      - ./docker/mysql:/etc/mysql/conf.d/:ro
  app:
    build:
     context: .
     dockerfile: ./Dockerfile
    environment:
      PORT: '3000'
      MIRIN_BASE_URL: https://cookpad.com
      MIRIN_DATABASE_USER: mirin
      MIRIN_DATABASE_PASSWORD: mirin
      MIRIN_DATABASE_HOST: mysql
      MIRIN_DATABASE_PORT: 3306
      MIRIN_DATABASE_POOLSIZE: 5
      MIRIN_DATABASE_NAME: mirin
    ports:
      - "3000:3000"
    links:
      - mysql
